### ISSUE TITLE
Add game data page

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/leaves-and-shadows-web#15]
The purpose of this issue is to add game data page to the Leaves & Shadows website, showing up a dynamic page to query all the characters and another one to query all the worlds from the Fall of the Gods universe.

# Tasks
- [x] List every character inside a grid in its respective page.
- [x] Add a world filter that allows users to filter characters for a specific world.
- [x] Add a name filter that allows users to filter characters by the name the user types.
- [x] Generate dynamic page for each character.
- [ ] ~List every world inside a grid in its respective page.~

In order for this issue to be closed, all tasks should be completed.
