### ISSUE TITLE
Add achievements page

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/leaves-and-shadows-web#16]
The purpose of this issue is to add achievements page to the Leaves & Shadows website, showing every achievement of the logged in user.

# Tasks

- [x] Put a button on the user information drawer to access its achievements page.
- [x] List every achievement of the game, no matter if the user has achieved it or not.
- [x] Hide the information of the achievements yet to unlock by the user.
- [x] Add a filter for locked and unlocked achievements.

In order for this issue to be closed, all tasks should be completed.
