### ISSUE TITLE
Finish dashboard page

### ISSUE THREAD

**Issue by GY-CODING** [GY-CODING/leaves-and-shadows-web#17]
The purpose of this issue is to finish dashboard page.

# Tasks

- [x] Add first page background gif with the game logo and a button to download the game.
- [x] Add a navbar displaying the game logo and a button to manage user accounts functionalities.
- [x] Add a section where user will be able to read a brief summary of the game story and the whole universe story.
- [ ] Add a section where user will be able to read about both of the main characters displayed in this game.

In order for this issue to be closed, all tasks should be completed.
